version: '3.8'

services:
  webapp:
    build:
      context: ./Web_app
    ports:
      - "3000:80"  # Map port 3000 on host to port 3000 on webapp container
    depends_on:
      - data-collector
      - data-analyzer
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "5001:5001"
    depends_on:
      - data-collector
      - data-analyzer

  data-collector:
    build:
      context: ./Data_collector_app
    ports:
      - "5003:5003"

  data-analyzer:
    build:
      context: ./Data_analyzer_app
    ports:
      - "5002:5002"  # Map port 5000 on host to port 5000 on data-analyzer container


