steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/volunteer-management/imagetest1', '.']
  dir: './Frontend/'

# Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/volunteer-management/imagetest1']

# Deploy the Docker container
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-d', '-p', '80:80', 'gcr.io/volunteer-management/imagetest1']

options:
  logging: CLOUD_LOGGING_ONLY  # or use NONE if you don't need Cloud Logging

